import { StyleSheet } from "react-native";

const COLORS = {
  primary: '#262a4f',
  secondary: '#a9acd6',
  background: '#f5f6fa',
  white: '#FFFFFF',
  textDark: '#0F172A',
  textGray: '#374151',
};

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: COLORS.background},

  /* ---------- HEADER ---------- */
  header: {
    paddingBottom: 10,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    elevation: 8,
    backgroundColor: COLORS.white,
    shadowColor: '#64748B',
    shadowOpacity: 0.12,
    shadowOffset: {width: 0, height: 6},
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingBottom: 16,
    paddingHorizontal: 18,
  },
  logoButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  logoImage: {width: 40, height: 40},
  headerCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 10,
  },
  headerTitle: {
    fontSize: 20,
    color: COLORS.primary,
    fontWeight: '700',
  },
  subTitle: {color: COLORS.secondary, fontSize: 12, marginTop: 2},
  refreshButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshIcon: {fontSize: 18, fontWeight: '700', color: COLORS.primary},

  /* ---------- TABS ---------- */
  tabRow: {
    flexDirection: 'row',
    marginTop: 16,
    marginHorizontal: 12,
    backgroundColor: '#e9e9f2',
    borderRadius: 30,
    padding: 4,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 25,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  activeTabButton: {backgroundColor: COLORS.primary},
  tabText: {fontSize: 14, color: COLORS.primary, fontWeight: '500'},
  activeTabText: {color: '#fff', fontWeight: '700'},
  wishlistBadge: {
    backgroundColor: '#e74c3c',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 6,
  },
  wishlistBadgeText: {color: '#fff', fontSize: 11, fontWeight: '700'},

  /* ---------- CARD – ORIGINAL DESIGN ---------- */
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginVertical: 8,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  carImage: {
    width: '100%',
    height: 160,
    resizeMode: 'cover',
  },
  imageLoader: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heartIcon: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#00000060',
    borderRadius: 20,
    padding: 6,
  },
  scrapBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#e63946',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  scrapText: {color: '#fff', fontSize: 10, fontWeight: '600'},
  cardDetails: {padding: 10},
  carName: {fontSize: 16, fontWeight: '700', color: COLORS.primary},
  locationRow: {flexDirection: 'row', alignItems: 'center', marginTop: 4},
  locationTextSmall: {fontSize: 12, color: '#666', marginLeft: 4},
  carInfo: {fontSize: 12, color: '#777', marginTop: 4},

  /* ---------- EMPTY STATE ---------- */
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 8,
    color: COLORS.primary,
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#777',
    textAlign: 'center',
    marginTop: 4,
  },

  /* ---------- MODAL ---------- */
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBox: {
    backgroundColor: '#fff',
    borderRadius: 16,
    width: '95%',
    maxHeight: '90%',
    overflow: 'hidden',
  },
  modalCloseIcon: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 20,
    padding: 8,
    zIndex: 10,
  },
  loadingImageContainer: {
    width: '100%',
    height: 240,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
  },
  loadingText: {fontSize: 14, color: '#666'},
  imageScrollView: {width: '100%', height: 240},
  imageIndicator: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignSelf: 'center',
    borderRadius: 12,
    marginTop: -30,
    marginBottom: 10,
  },
  imageIndicatorText: {color: '#fff', fontSize: 12, fontWeight: '500'},
  modalContent: {padding: 20},
  modalYear: {fontSize: 16, color: '#666', fontWeight: '500', marginBottom: 4},
  modalTitle: {fontSize: 24, fontWeight: '700', color: '#000', marginBottom: 4},
  modalSubtitle: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
    marginBottom: 16,
  },
  badgeRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12},
  badge: {
    borderWidth: 1.5,
    borderColor: '#000',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 8,
    marginBottom: 8,
  },
  badgeText: {fontSize: 13, fontWeight: '600', color: '#000'},
  sectionContainer: {marginTop: 24},
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#000',
    marginBottom: 16,
  },
  infoCard: {backgroundColor: '#f8f8f8', borderRadius: 12, padding: 16},
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  infoItem: {flex: 1, alignItems: 'flex-start'},
  infoLabel: {fontSize: 13, color: '#666', marginTop: 6, marginBottom: 4},
  infoValue: {fontSize: 15, fontWeight: '700', color: '#000'},
  featuresCard: {backgroundColor: '#f8f8f8', borderRadius: 12, padding: 16},
  featureRow: {flexDirection: 'row', alignItems: 'center', marginBottom: 16},
  featureText: {fontSize: 16, fontWeight: '600', color: '#000', marginLeft: 12},
  locationInfo: {flexDirection: 'row', alignItems: 'center', marginTop: 12},
  locationText: {fontSize: 14, color: '#333', marginLeft: 8, fontWeight: '500'},
});

export default styles;
